AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for basic-aws-apigateway-demo
  
Resources:
  
  ResidenceSystemApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: stage

  RequirementsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      ContentUri: layer

  LoginService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/login.handler
      Runtime: python3.11
      Layers:
        - !Ref RequirementsLayer
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref ResidenceSystemApiGateway
            Path: /login
            Method: POST

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "USER"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
            
Outputs:
  ResidenceSystemApiGateway:
    Description: 'API Gateway endpoint URL for Staging stage for Hello World function'
    Value: !Sub 'https://${ResidenceSystemApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Staging/hello/'
  ResidenceSystemApiGatewayRestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref ResidenceSystemApiGateway
    Export:
      Name: ResidenceSystemApiGateway-RestApiId
  ResidenceSystemApiGatewayRootResourceId:
    Value: !GetAtt ResidenceSystemApiGateway.RootResourceId
    Export:
      Name: ResidenceSystemApiGateway-RootResourceId