on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - prod
      

jobs:
  
  build-deploy:
    environment: "${{ inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build --use-container

      - name: Upload artifacts to production artifact buckets
        run: |
          sam package \
            --s3-bucket  residence-system-back-end \
            --region us-east-1 \
            --output-template-file packaged.yaml


      - name: sam deploy
        run: | 
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset  --template packaged.yaml \ 
              --stack-name residence-api-stack --s3-bucket residence-system-back-end --capabilities CAPABILITY_IAM --region us-east-1